[project]
name = "package"
version = "1.0.0"
description = "Package for Ballsdex with DexI"
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "discord.py>=2.5.0",
]

[tool.dexi]
public = true
ballsdex-version = ">=2.25.0"
include-license = true

[tool.dexi.package]
source = "Package"
target = "say"
exclude = ["hide.py"]

[tool.dexi.app]
source = "App"
target = "say"
models = "models.py"
